version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - db
    environment:
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  client:
    container_name: client
    image: node:alpine
    working_dir: /app
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app 
    command: yarn dev 